# -*- coding: utf-8 -*-
"""Imperial AI Capstone 5_1_TTS_60_20_20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dy-SDLGNYkgl7vFGOJUoJ3qlvD3c_M_w
"""

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Load the default wine dataset
data = load_wine()
X = data.data
y = data.target

# Split data into train (60%), validation (20%) and test (20%)sets
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42, stratify=y_train_val
)

# 0.25 * 0.80 ≈ 0..2, so validation is ~20% of total
print(len(X), len(X_train), len(X_val), len(X_test))

# Fit the logistic regression model
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# Evaluate the validation set
val_preds = model.predict(X_val)
val_accuracy = accuracy_score(y_val, val_preds)
print(f"Validation Accuracy: {val_accuracy:.4f}")

# Evaluate the test set
test_preds = model.predict(X_test)
test_accuracy = accuracy_score(y_test, test_preds)
print(f"Test Accuracy: {test_accuracy:.4f}")

# Detailed classification report on test set
print("\nClassification Report on Test Set:")
print(classification_report(y_test, test_preds, target_names=data.target_names))